import { Resource } from "../../types";

export const DUMMY_RESOURCES: Resource[] = [
  {
    _id: "h1",
    name: "KGMU (King George Medical University)",
    type: "hospital",
    address: "Shah Mina Rd, Chowk, Lucknow, Uttar Pradesh 226003",
    district: "Lucknow",
    head_of_dept: "Dr. Soniya Nityanand (VC)",
    contact_number: "0522-2258880",
    capacity: {
      total: 4500,
      occupied: 3890,
      label: "Beds",
    },
    stats: {
      critical_patients: 142,
      daily_footfall: 12000,
    },
    vehicles: [
      {
        _id: "v1",
        type: "ambulance",
        plate_number: "UP-32-BG-1001",
        status: "available",
      },
      {
        _id: "v2",
        type: "ambulance",
        plate_number: "UP-32-BG-1002",
        status: "busy",
      },
      {
        _id: "v3",
        type: "ambulance",
        plate_number: "UP-32-BG-1003",
        status: "maintenance",
      },
      {
        _id: "v4",
        type: "ambulance",
        plate_number: "UP-32-BG-1004",
        status: "available",
      },
    ],
    staff: [
      {
        _id: "s1",
        name: "Dr. Ravi Kant",
        role: "Senior Surgeon",
        specialization: "Cardiology",
        status: "on_duty",
        shift_start: "08:00",
        shift_end: "16:00",
        contact: "9876543210",
      },
      {
        _id: "s2",
        name: "Dr. Meera Singh",
        role: "Resident Doctor",
        specialization: "Pediatrics",
        status: "off_duty",
        shift_start: "16:00",
        shift_end: "00:00",
        contact: "9876543211",
      },
      {
        _id: "s3",
        name: "Nurse Anjali",
        role: "Head Nurse",
        status: "on_duty",
        shift_start: "07:00",
        shift_end: "15:00",
        contact: "9876543212",
      },
      {
        _id: "s4",
        name: "Dr. P.K. Das",
        role: "Consultant",
        specialization: "Neurology",
        status: "leave",
        shift_start: "09:00",
        shift_end: "17:00",
        contact: "9876543213",
      },
    ],
  },
  {
    _id: "p1",
    name: "Hazratganj Kotwali",
    type: "police_station",
    address: "Hazratganj, Lucknow, Uttar Pradesh 226001",
    district: "Lucknow",
    head_of_dept: "Inspector Akhilesh Mishra",
    contact_number: "0522-2222222",
    capacity: {
      total: 20,
      occupied: 12,
      label: "Holding Cells",
    },
    stats: {
      pending_cases: 45,
      daily_footfall: 150,
    },
    vehicles: [
      {
        _id: "pv1",
        type: "police_car",
        plate_number: "UP-32-AG-0100",
        status: "available",
      },
      {
        _id: "pv2",
        type: "police_car",
        plate_number: "UP-32-AG-0101",
        status: "busy",
      },
      {
        _id: "pv3",
        type: "police_car",
        plate_number: "UP-32-AG-0102",
        status: "busy",
      },
    ],
    staff: [
      {
        _id: "ps1",
        name: "Constable Rajesh",
        role: "Constable",
        status: "on_duty",
        shift_start: "06:00",
        shift_end: "14:00",
        contact: "8877665544",
      },
      {
        _id: "ps2",
        name: "SI Vinod Kumar",
        role: "Sub-Inspector",
        status: "on_duty",
        shift_start: "08:00",
        shift_end: "20:00",
        contact: "8877665545",
      },
      {
        _id: "ps3",
        name: "Constable Suresh",
        role: "Driver",
        status: "off_duty",
        shift_start: "14:00",
        shift_end: "22:00",
        contact: "8877665546",
      },
    ],
  },
  {
    _id: "sc1",
    name: "City Montessori School (CMS)",
    type: "school",
    address: "Gomti Nagar Extension, Lucknow",
    district: "Lucknow",
    head_of_dept: "Mrs. Geeta Gandhi",
    contact_number: "0522-2300001",
    capacity: {
      total: 5000,
      occupied: 4800,
      label: "Students",
    },
    staff: [
      {
        _id: "t1",
        name: "Mrs. Sharma",
        role: "Principal",
        status: "on_duty",
        shift_start: "07:30",
        shift_end: "15:30",
        contact: "7766554433",
      },
      {
        _id: "t2",
        name: "Mr. Verma",
        role: "Senior Teacher",
        status: "on_duty",
        shift_start: "07:30",
        shift_end: "14:30",
        contact: "7766554434",
      },
    ],
  },
];
