import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { Screen } from '@/components/screen';
import { Button, Card, SectionTitle, StateMessage } from '@/components/ui';
import { ApiError, api } from '@/services/api';
import { queueMoneyTransaction, readCachedMoneyOverview } from '@/services/money-offline';
import { radii, spacing, type ThemeColors } from '@/theme';
import { useLifeOSTheme } from '@/theme/provider';
import type { MoneyAccount, MoneyAccountType, MoneyTransactionType } from '@/types/api';
import { useAuth } from '@/auth/provider';

const CAPTURE_TYPES: MoneyTransactionType[] = ['expense', 'income', 'transfer', 'refund', 'deposit_funding', 'investment_contribution', 'debt_payment', 'fee'];
const TYPE_LABELS: Record<MoneyTransactionType, string> = { expense: 'Expense', income: 'Income', transfer: 'Transfer', refund: 'Refund', fee: 'Fee', deposit_funding: 'Deposit', investment_contribution: 'Invest', debt_payment: 'Debt pay', adjustment: 'Adjustment' };
const ACCOUNT_TYPES: MoneyAccountType[] = ['bank', 'cash', 'credit_card', 'loan', 'deposit', 'investment', 'manual_asset', 'manual_liability'];

export default function AddMoneyScreen() {
  const params = useLocalSearchParams<{ kind?: string; type?: string }>();
  const initialType = CAPTURE_TYPES.includes(params.type as MoneyTransactionType) ? params.type as MoneyTransactionType : 'expense';
  const [mode, setMode] = useState<'transaction' | 'account'>(params.kind === 'account' ? 'account' : 'transaction');
  return <><Stack.Screen options={{ title: mode === 'account' ? 'Add account' : 'Add money event' }} /><Screen eyebrow="Account semantics first" title={mode === 'account' ? 'New account' : 'What happened?'}><View style={stylesFor(useLifeOSTheme().colors).switcher}><Mode label="Transaction" selected={mode === 'transaction'} onPress={() => setMode('transaction')} /><Mode label="Account" selected={mode === 'account'} onPress={() => setMode('account')} /></View>{mode === 'account' ? <AccountForm /> : <TransactionForm initialType={initialType} />}</Screen></>;
}

function Mode({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { colors } = useLifeOSTheme(); const styles = stylesFor(colors); return <Pressable onPress={onPress} style={[styles.mode, selected && styles.modeSelected]}><Text style={[styles.modeText, selected && styles.modeTextSelected]}>{label}</Text></Pressable>; }

function AccountForm() {
  const router = useRouter(); const queryClient = useQueryClient(); const { colors } = useLifeOSTheme(); const styles = stylesFor(colors);
  const [name, setName] = useState(''); const [institution, setInstitution] = useState(''); const [openingBalance, setOpeningBalance] = useState(''); const [type, setType] = useState<MoneyAccountType>('bank'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setError(''); try { await api.createMoneyAccount({ name, institution, openingBalance, type, currency: 'INR', includeInNetWorth: true }); await queryClient.invalidateQueries({ queryKey: ['money-overview'] }); router.back(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create account.'); } finally { setSaving(false); } };
  return <View style={styles.form}><SectionTitle title="Account details" detail="INR" /><Card><View style={styles.fields}><Field label="Account name" value={name} onChangeText={setName} placeholder="HDFC Savings" /><Field label="Institution (optional)" value={institution} onChangeText={setInstitution} placeholder="HDFC Bank" /><Text style={styles.label}>Account type</Text><View style={styles.chips}>{ACCOUNT_TYPES.map((item) => <Choice key={item} label={item.replaceAll('_', ' ')} selected={type === item} onPress={() => setType(item)} />)}</View><Field keyboardType="decimal-pad" label={['credit_card', 'loan', 'manual_liability'].includes(type) ? 'Opening amount owed' : 'Opening balance'} value={openingBalance} onChangeText={setOpeningBalance} placeholder="0.00" /><Text style={styles.help}>Opening value is stored as an adjustment, not income. Account type cannot be casually changed after activity.</Text></View></Card>{error ? <Text style={styles.error}>{error}</Text> : null}<Button disabled={saving || !name.trim()} label={saving ? 'Saving…' : 'Create account'} onPress={() => void save()} /></View>;
}

function TransactionForm({ initialType }: { initialType: MoneyTransactionType }) {
  const router = useRouter(); const queryClient = useQueryClient(); const { colors } = useLifeOSTheme(); const { user } = useAuth(); const styles = stylesFor(colors); const userId = user!.id;
  const accounts = useQuery({ queryKey: ['money-accounts', userId], queryFn: async ({ signal }) => { try { return await api.moneyAccounts(signal); } catch (error) { const cached = await readCachedMoneyOverview(userId); if (cached) return cached.accounts; throw error; } } });
  const [type, setType] = useState(initialType); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [sourceAccountId, setSource] = useState(''); const [destinationAccountId, setDestination] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const needsSource = !['income', 'refund'].includes(type); const needsDestination = !['expense', 'fee'].includes(type); const twoLeg = needsSource && needsDestination;
  const valid = amount && (!needsSource || sourceAccountId) && (!needsDestination || destinationAccountId) && sourceAccountId !== destinationAccountId;
  const input = useMemo(() => ({ semanticType: type, amount, occurredOn: date, description: description || TYPE_LABELS[type], category, sourceAccountId: sourceAccountId || undefined, destinationAccountId: destinationAccountId || undefined }), [type, amount, date, description, category, sourceAccountId, destinationAccountId]);
  const save = async () => { setSaving(true); setError(''); try { await api.createMoneyTransaction(input); await queryClient.invalidateQueries({ queryKey: ['money-overview', userId] }); router.back(); } catch (reason) { if (reason instanceof ApiError) setError(reason.message); else { await queueMoneyTransaction(userId, input); await queryClient.invalidateQueries({ queryKey: ['money-pending', userId] }); router.back(); } } finally { setSaving(false); } };
  if (accounts.isPending) return <StateMessage loading title="Loading accounts" message="Preparing valid source and destination choices." />;
  if (accounts.isError) return <StateMessage title="Accounts unavailable" message="Reconnect before creating a new entry, or pull down from Money to use cached state." />;
  if (!accounts.data.length) return <StateMessage icon="wallet-plus-outline" title="Add an account first" message="Every money event needs an account movement." />;
  return <View style={styles.form}><Text style={styles.label}>Semantic type</Text><View style={styles.chips}>{CAPTURE_TYPES.map((item) => <Choice key={item} label={TYPE_LABELS[item]} selected={type === item} onPress={() => { setType(item); setSource(''); setDestination(''); }} />)}</View><View style={styles.notice}><MaterialCommunityIcons color={colors.primary} name={twoLeg ? 'swap-horizontal' : type === 'expense' || type === 'fee' ? 'cart-outline' : 'bank-transfer-in'} size={20} /><Text style={styles.noticeText}>{twoLeg ? 'Moves value between owned positions; excluded from spending.' : type === 'expense' || type === 'fee' ? 'Counts as consumption or cost in cashflow.' : 'Brings external value into an account.'}</Text></View><Card><View style={styles.fields}><Field keyboardType="decimal-pad" label="Amount" value={amount} onChangeText={setAmount} placeholder="0.00" />{needsSource ? <AccountChoices title={twoLeg ? 'From account' : 'Paid from'} accounts={accounts.data} selected={sourceAccountId} excluded={destinationAccountId} onSelect={setSource} /> : null}{needsDestination ? <AccountChoices title={twoLeg ? 'To account / position' : 'Received into'} accounts={accounts.data} selected={destinationAccountId} excluded={sourceAccountId} onSelect={setDestination} /> : null}<Field label="Description" value={description} onChangeText={setDescription} placeholder="What was this for?" /><Field label="Category (optional)" value={category} onChangeText={setCategory} placeholder="Food, salary, housing…" /><Field label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-09-01" /></View></Card>{error ? <Text style={styles.error}>{error}</Text> : null}<Button disabled={saving || !valid} label={saving ? 'Saving…' : 'Save money event'} onPress={() => void save()} /><Text style={styles.help}>If the network drops, this manual entry stays on-device and syncs the next time Money opens.</Text></View>;
}

function AccountChoices({ title, accounts, selected, excluded, onSelect }: { title: string; accounts: MoneyAccount[]; selected: string; excluded: string; onSelect: (id: string) => void }) { return <View style={{ gap: spacing.sm }}><Text style={stylesFor(useLifeOSTheme().colors).label}>{title}</Text><View style={stylesFor(useLifeOSTheme().colors).chips}>{accounts.filter((account) => account.id !== excluded).map((account) => <Choice key={account.id} label={`${account.name} · ${formatMoney(account.balance)}`} selected={selected === account.id} onPress={() => onSelect(account.id)} />)}</View></View>; }
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { colors } = useLifeOSTheme(); const styles = stylesFor(colors); return <Pressable onPress={onPress} style={[styles.chip, selected && styles.chipSelected]}><Text style={[styles.chipText, selected && styles.chipTextSelected]}>{label}</Text></Pressable>; }
function Field(props: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: 'default' | 'decimal-pad' }) { const { colors } = useLifeOSTheme(); const styles = stylesFor(colors); return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput {...props} accessibilityLabel={props.label} placeholderTextColor={colors.inkMuted} style={styles.input} /></View>; }
function formatMoney(value: string) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value)); }

const stylesFor = (colors: ThemeColors) => StyleSheet.create({
  switcher: { backgroundColor: colors.surfaceMuted, borderRadius: radii.pill, flexDirection: 'row', padding: spacing.xs }, mode: { alignItems: 'center', borderRadius: radii.pill, flex: 1, padding: spacing.md }, modeSelected: { backgroundColor: colors.surface }, modeText: { color: colors.inkMuted, fontSize: 13, fontWeight: '800' }, modeTextSelected: { color: colors.ink },
  form: { gap: spacing.lg }, fields: { gap: spacing.lg }, field: { gap: spacing.sm }, label: { color: colors.ink, fontSize: 12, fontWeight: '800' }, input: { backgroundColor: colors.surfaceMuted, borderColor: colors.border, borderRadius: radii.sm, borderWidth: 1, color: colors.ink, fontSize: 16, minHeight: 48, paddingHorizontal: spacing.md },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, chip: { backgroundColor: colors.surfaceMuted, borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, chipSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.ink, fontSize: 12, fontWeight: '700', textTransform: 'capitalize' }, chipTextSelected: { color: colors.primaryContrast },
  notice: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: radii.sm, flexDirection: 'row', gap: spacing.md, padding: spacing.md }, noticeText: { color: colors.ink, flex: 1, fontSize: 12, lineHeight: 18 }, help: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, textAlign: 'center' }, error: { color: colors.danger, fontSize: 13, fontWeight: '700', textAlign: 'center' },
});
